coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 1%
    patch:
      default:
        target: 100%

ignore:
  - "sensors/management/**/*"
  - "node_modules/**/*"
  - "*/migrations/*"
  - "manage.py"