# Include the specific folders you want
source = 
    sensors
    core

# Exclude management commands and test files from being measured
omit =
    sensors/management/*
    manage.py

[report]
# Show which lines are missing
show_missing = True
# Check for branch coverage (handles 'if' statements)
precision = 2

[html]
directory = htmlcov