# Generated by Django 6.0 on 2025-12-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_add_image_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='__str__',
        ),
        migrations.RemoveField(
            model_name='report',
            name='__str__',
        ),
    ]
