# Generated by Django 6.0 on 2025-12-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_status',
            field=models.CharField(default='Safe', max_length=20),
        ),
    ]
