# Generated by Django 6.0 on 2026-01-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_remove_maintenance_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='technician_notes',
            field=models.TextField(blank=True, help_text='Notes from the technician after maintenance.', null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
