# Generated by Django 6.0 on 2026-01-11 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_alter_maintenance_maintenance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselayout',
            name='image',
            field=models.ImageField(upload_to='layouts/'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in_progress'), ('Completed', 'completed'), ('Rejected', 'rejected'), ('Completed with damages', 'completed_with_damages')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensors.houselayout'),
        ),
    ]
