# Generated by Django 4.2.11 on 2026-01-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_alter_report_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='trigger_gas_level',
        ),
        migrations.AlterField(
            model_name='report',
            name='cause',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='fire_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
