# Generated by Django 4.2.11 on 2026-03-16 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sensors", "0015_alter_sensordatalog_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The Commander who approved this report",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Checked officially by KB or PBK"
            ),
        ),
    ]
