# Generated by Django 5.0.4 on 2026-06-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0018_alter_sensordatalog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text="User's or Firefighter's unique Telegram Chat ID", max_length=50, null=True),
        ),
    ]
